### PR TITLE
Bring dependencies and plugins up-to-date

### PR DESCRIPTION
**Pull request by hazendaz**

### CODE REVIEW

**Comment by hazendaz** [comment]
@stanislawosinski This PR brings dependencies all up-to-date while remaining on guava 20 (ie 21 required jdk8 so didn't go there).  Once merged, can you push a micro release?

**Comment by stanislawosinski** [comment]
Thanks for the PR, I'll make the release later this week.

**Comment by stanislawosinski** [comment]
Version 0.2.13 should be on Maven Central now.

**Comment by hazendaz** [comment]
Thank you!

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Pull request merged**
