### PR TITLE
Updating plugins and dependencies

### PR DESCRIPTION
**Pull request by hazendaz**

### CODE REVIEW

**Comment by hazendaz** [comment]
Any chance on getting this in as well as getting a release since the prior PR I pushed reworked some dependency usage?

**Comment by hazendaz** [comment]
@stanislawosinski I've made some additional dependency updates.  Any chance of getting this applied and released?

**Comment by stanislawosinski** [comment]
Thanks for the PR, @hazendaz! I'm trying to get this released, but running Maven (``mvn -Prelease clean verify site``), I'm getting an error like this:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.5:site (default-site) on project smartsprites: Error generating versions-maven-plugin:2.2:property-updates-report: only whitespace content allowed before start tag and not \u10f (position: START_DOCUMENT seen \u10f... @1:1)
```

(full log here: http://builds.carrot2.org/browse/SMARTSPRITES-SOFTWARE-DIST-20/log)

I'm not too much of a Maven expert, any idea how to fix this? I don't even seem to be able to find the path to the offending file.

**Comment by hazendaz** [comment]
Looks like a problem with pom where it switched to bom.  I've seen this a bunch of times.  It's usually a bad non UTF 8 character in the pom.  Only way I know to fix it is to create a completely new pom and copy the contents from original into new one.  Or disable the version plugin.  I'll try to track down the root cause tonight.


Sent from Outlook Mobile






On Mon, Mar 7, 2016 at 3:28 AM -0800, "Stanisław Osiński" <notifications@github.com> wrote:





Thanks for the PR, @hazendaz! I'm trying to get this released, but running Maven (``mvn -Prelease clean verify site``), I'm getting an error like this:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.5:site (default-site) on project smartsprites: Error generating versions-maven-plugin:2.2:property-updates-report: only whitespace content allowed before start tag and not \u10f (position: START_DOCUMENT seen \u10f... @1:1)
```

(full log here: http://builds.carrot2.org/browse/SMARTSPRITES-SOFTWARE-DIST-20/log)

I'm not too much of a Maven expert, any idea how to fix this? I don't even seem to be able to find the path to the offending file.

---

**Comment by stanislawosinski** [comment]
Good point, thanks! Removing BOM from pom.xml did the trick. I've just made the release, it should propagate soon.

**Comment by hazendaz** [comment]
Awesome!  Thanks


Sent from Outlook Mobile






On Mon, Mar 7, 2016 at 4:33 AM -0800, "Stanisław Osiński" <notifications@github.com> wrote:





Good point, thanks! Removing BOM from pom.xml did the trick. I've just made the release, it should propagate soon.

---

**Pull request merged**
