### PR TITLE
Modernizing library

### PR DESCRIPTION
**Pull request by hazendaz**
* Fixed Junit

    * Use only non-deprecated Junit imports
    * added .5 delta to satisfy latest junit.

  * Maven Note

    * Maven build fails when test\non-default\output\dir\absolute-path is
      missing.  Added temporary text file to mark issue.

  * Interface Cleanup

    * Removed public from methods in interface as they are implied by the
      context

  * Removed unnecessary location defined by import

    * java.security already an import.  No conflicts exist, so removed it from
      MessageDigest as indicated per PMD.

  * Updated code to use lasest ant library

  * POM Cleanup

    * Added versions plugin to see what is out of date.
    * Updated all out of date plugins
    * Fixed some spelling mistakes
    * Override PMD with latest.
    * Updated to java 6 build
    * Updated dependencies to latest
    * Overall build time changes by very little as a result of these changes.

  * Updated code to use latest guava library

  * Switch localized StringBuffer to StringBuilder

  * Replace fest-assert with assertj

  * Replace commons-lang with guava

### CODE REVIEW

**Comment by hazendaz** [comment]
I'm willing to rework the commit line on this once this is reviewed assuming it will be accepted.  This brings it completely up to date as of 1/4/2015 :)

**Comment by hazendaz** [comment]
Any status on this PR?

**Comment by hazendaz** [comment]
Hi again!  I rebased so this is clean again as well as completely reworked the commit lines so it is easy to follow.  @stanislawosinski can you take a look at this?  We have been using this in a production setting for a long time now without any issues.  I would like to get this on the master if possible.  If you need smaller PR requests I can do that as well.  Thanks.

**Comment by stanislawosinski** [comment]
Thanks for the PR! I see that the build passed (http://builds.carrotsearch.com/browse/SMARTSPRITES-SOFTWARE-15).

**Comment by hazendaz** [comment]
You're welcome and thanks for merging.

--- Original Message ---

**Pull request merged**
